import:
  files:
    - ["./node_modules/sense-extension-utils/dist/extUtils.js", "./.tmp/lib/external/sense-extension-utils"]
wbfolder:
  enabled: false
localExtensionDir: ""
deployment:
  toLocal:
    enabled: false
