packageName: "sense-navigation"
import:
  files:
    - ["./node_modules/sense-extension-utils/dist/extUtils.js", "./.tmp/lib/external/sense-extension-utils"]
wbfolder:
  enabled: false
localExtensionDir: ""
deployment:
  toLocal:
    enabled: false
  toSsh:
    enabled: true
    host: "192.168.56.13"
    port: 22
    username: "stefanwalther"
    password: "Test1234"
    dest: "/cygdrive/c/Users/stefanwalther/Documents/Qlik/Sense/Extensions/sense-navigation"
